### ISSUE TITLE
Title Page

### ISSUE THREAD

**Issue by VictorArchela** [stolksdorf/naturalcrit#122]
Is there a way to make title pages?

So far I'm going to have to make the text a picture and import it.

What I'd like to know how to do is how to take the page footer out, is that possible?

**Comment by stolksdorf** [comment]
> Is there a way to make title pages?

Not easy and built-in

> So far I'm going to have to make the text a picture and import it.

Sounds like a good solution. You could also mess around with CSS.

> What I'd like to know how to do is how to take the page footer out, is that possible?

```css
<style>
   .phb:first-child::after{display:none;}
</style>
```
